version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DRIVER_CLASS_NAME=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - PASSWORD=admin
      - USERNAME=admin

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD:admin
      - POSTGRES_USER:admin
      - POSTGRES_DB:postgres

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DRIVER_CLASS_NAME=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://ewm-db:6432/postgres
      - PASSWORD=admin
      - USERNAME=admin

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6432:6432"
    environment:
      - POSTGRES_PASSWORD:admin
      - POSTGRES_USER:admin
      - POSTGRES_DB:postgres